### PR TITLE
OpenChat - Message posting now uses XHR requests

### PR DESCRIPTION
**Pull request by lkellar**
Message posting is now done through XHR requests, to avoid page refreshes. 

Also, I changed the time_passed function to use singular units if the time_passed thing is singular (1 hour, 1 minute, etc)

### CODE REVIEW

**Comment by jpsank** [comment]
@katzrkool Does this work when a user submits a message on a page other than the first one?

**Comment by lkellar** [comment]
That’s a great question, I have no idea

**Comment by lkellar** [comment]
Maybe we should add a check if the user isn’t on page 1, redirect them after submitting

**Comment by lkellar** [comment]
@puffyboa It now redirects the client back to Page 1 after message submission if they're on some other page.

**Pull request merged**
